/**
 * @typedef {String} ActionType
 */
export const ACTION_TYPE = {
  UNKNOWN: 'ACTION_TYPE.UNKNOWN',

  COMBAT_ROUND: {
    INITIATIVE: 'ACTION_TYPE.COMBAT_ROUND.INITIATIVE',
    MACRO: 'ACTION_TYPE.COMBAT_ROUND.MACRO',
    ATTACK_WITH_WEAPON: 'ACTION_TYPE.COMBAT_ROUND.ATTACK_WITH_WEAPON',
    SKILL_CAST: 'ACTION_TYPE.COMBAT_ROUND.SKILL_CAST',
    ITEM_USE: 'ACTION_TYPE.COMBAT_ROUND.ITEM_USE',
    ITEM_ACQUIRE: 'ACTION_TYPE.COMBAT_ROUND.ITEM_ACQUIRE',

    FAMILIAR: 'ACTION_TYPE.COMBAT_ROUND.FAMILIAR',
  },
}

export default ACTION_TYPE;