/** @type {String} AscensionDifficulty */
export const ASCENSION_DIFFICULTY = {
  CASUAL: 'ASCENSION_DIFFICULTY.CASUAL',
  NORMAL: 'ASCENSION_DIFFICULTY.NORMAL',
  HARDCORE: 'ASCENSION_DIFFICULTY.HARDCORE',
};