import * as ENTITIES from 'constants/ENTITIES';

export const BANISHERS = [
  ENTITIES.LOUDER_THAN_BOMB,
  ENTITIES.HAROLDS_BELL,
  ENTITIES.TRYPTOPHAN_DART,
  ENTITIES.REFLEX_HAMMER,
  ENTITIES.USE_THE_FORCE,
  ENTITIES.BATTER_UP,
]