/**
 * https://kol.coldfront.net/thekolwiki/index.php/Semi-Rare_Adventures
 */
export const SEMIRARE_ENCOUNTERS = [
  'Where There\'s Smoke...',
  'A Shark\'s Chum',
  'Bram the Stoker',
  'Play Misty For Me',
  'Like the Sunglasses, But Less Comfortable',
  'The Pilsbury Doughjerk',
  'full-length mirror',
  'In the Still of the Alley',
  'Natural Selection',
  '7-Foot Dwarf Foreman',
  'Not Quite as Cold as Ice',
  'The Bleary-Eyed Cyclops',
  'Bad ASCII Art',
  'Oh, There Have it Gone',
  'Synecdoche, Twin Peak',
  'It\'s a Gas Gas Gas',
  // 'Methinks the Protesters Doth Protest Too Little', // probably clover
  'Red Fox',
  'Prior to Always',
  'How Does He Smell?',
  'Fit and Finish',
  'Ahead of the Game',
  'All The Rave',
  'Le Chauve-Souris du Parfum',
  'Hands On',
  'Knob Goblin Elite Guard Captain',
  'You Can Top Our Desserts, But You Can\'t Beat Our Meats',
  'Rokay, Raggy!',
  'A Menacing Phantom',
  'Lunchboxing',
  'Knob Goblin Embezzler',
  'Filth, Filth, and More Filth',
  'Clay Is Great, But Leather Is Bether',
  'It\'s The Only Way To Be Sure',
  'Two Sizes Too Small',
  'Baa\'baa\'bu\'ran',
  'Some Bricks Do, In Fact, Hang in the Air',
  'Blaaargh! Blaaargh!',
  'Monty of County Crisco',
  'The Latest Sorcerous Developments',
  'Sand in the Vaseline',
  'Yo Ho Ho and a Bottle of Whatever This Is',
  'C. H. U. M. chieftain',
  'A Tight Squeeze',
  'Cold Comfort',
  'Juicy!',
  'Flowers for You',
  'Maybe It\'s a Sexy Snake!',
  'Deeps Impact',
  'The Haggling',
  'moister oyster',
  'Camera On, James',
  'Razor, Scooter',
  'Dragon the Line',
  'A Drawer of Chests',
  'The Time This Fire',
  'François Verte, Art Teacher',
  'Mrs. K, the Chemistry Teacher',
  'X-fingered Shop Teacher',
  'Through the Locking Glass',
];
/**
 * https://kol.coldfront.net/thekolwiki/index.php/Clover_Adventures
 */
export const CLOVER_ENCOUNTERS = [
  'Oot to Lunch',
  'Lemon Party Slot',
  'A Motor in your Head',
  'The Luckiest Gambler',
  'Where There\'s Smoke...',
  'Forward to the Past',
  'That\'s a Tidy Bowl, Man!',
  'Give me Your Nine',
  'Sweeping Up the Skeleton Bones',
  'With a Clatter',
  'Nicebox',
  'Dust to Dust',
  'It\'s Your Lucky Day!',
  'Best Served Cold',
  'Lucky You, Unlucky Hobo',
  'The Weathered Old Chap',
  'Either Ore',
  'Encino Penguin',
  'S&M 4-EVER',
  'The "Journalist"',
  'What Kind of Party Is This?',
  'Up From the Ground...',
  'Methinks the Protesters Doth Protest Too Little',
  'Knob Goblin Luck!',
  'Luck in the Kitchens',
  'Junction in the Trunction',
  'Believe it or Not',
  'I\'ve Gotta Crow',
  'The Boxer',
  'Only Dust and a Plaque',
  'Rolling the Bones',
  'How I Wonder What You\'re At',
  'What Can You Do?',
  'You Never Know What You\'re Gonna Find',
  'Wouldn\'t You Like to be a Pickle Too?',
  'Lucky, Lucky!',
  'Stage Fright',
  'Faux Fur Pas',
  'What the Cluck?',
  'A Role In the Hay',
  'Gno More Mr. Gnice Guy',
  'Forget Not That I am an Ass',
  'Some Things Never Change',
  'Lambda Upsilon Chi Kappa',
  // 'Lambda Upsilon Chi Kappa', // hmm
  'Batty About Fruit',
  'A Case of the Baskets',
  'Beginner\'s Luck',
];
/**
 * https://kol.coldfront.net/thekolwiki/index.php/Low_Key_Summer
 */
export const LOW_KEY_SUMMER_ENCOUNTERS = [
  'Lucky For You',
  'Just Taking the Opportunity to be a Pedant',
  'Midnight Sun',
  'Not a Lot Left',
  'Getting the Shaft Key',
  'Lost in Translation',
  'OF Ice & Yetis',
  'Batting a Thousand',
  'It\'s a Weremoose Key',
  'Into the Fryer',
  'Carpool Lane',
  'F=ma',
  'You Found a Thing, in Hell',
  'One Man\'s Trash is Presumably the Key to Another Man\'s Treasure',
  'Larrrst & Found',
  'B\'c\'le Up',
  'Yo-ho-ho in the Ho-ho-hold‎',
  'Hola, Amigos',
  'Decisions, Shmecisions',
  'Made of Stars',
  'Lore of the Roses',
  'Pork Key\'s Revenge',
  'Jerk-in-the-Box',
];
/**
 * https://kol.coldfront.net/thekolwiki/index.php/Low_Key_Summer
 */
export const FRIARS_QUEST_ENCOUNTERS = [
  'How Do We Do It? Quaint and Curious Volume!',
  'Strike One!',
  'Olive My Love To You, Oh.',
  'Dodecahedrariffic!',
  'Moon Over the Dark Heart',
  'Running the Lode',
  'I, Martin',
  'Imp Be Nimble, Imp Be Quick',
  'Deep Imp Act',
  'Imp Art, Some Wisdom',
  'A Secret, But Not the Secret You\'re Looking For',
  'Butter Knife? I\'ll Take the Knife',
];