/**
 * @typedef {String} EntryType
 */
export const ENTRY_TYPE = {
  UNKNOWN: 'ENTRY_TYPE.UNKNOWN',  
  MAFIA_LOG: 'ENTRY_TYPE.MAFIA_LOG',
  MAFIA_ASCENSION_INFO: 'ENTRY_TYPE.MAFIA_ASCENSION_INFO',
  MAFIA_EMPTY_CHECKPOINT: 'ENTRY_TYPE.MAFIA_EMPTY_CHECKPOINT',
  MAFIA_CLI: 'ENTRY_TYPE.MAFIA_CLI',
  SKILL_BREAKDOWN: 'ENTRY_TYPE.SKILL_BREAKDOWN',
  LOCATION_VISIT: 'ENTRY_TYPE.LOCATION_VISIT',
  NONCOMBAT_SKILL: 'ENTRY_TYPE.NONCOMBAT_SKILL',
  COMBAT_SKILL: 'ENTRY_TYPE.COMBAT_SKILL',
  COMBAT_ITEM: 'ENTRY_TYPE.COMBAT_ITEM',
  INVENTORY_USE: 'ENTRY_TYPE.INVENTORY_USE',
  ITEM_ACQUISITION: 'ENTRY_TYPE.ITEM_ACQUISITION',
  ENCOUNTER: 'ENTRY_TYPE.ENCOUNTER',  
}

export default ENTRY_TYPE;