/**
 * @typedef {String} EntryType
 */
export const ENTRY_TYPE = {
  UNKNOWN: 'ENTRY_TYPE.UNKNOWN',
  SNAPSHOT: {
    SKILL_BREAKDOWN: 'ENTRY_TYPE.SNAPSHOT.SKILL_BREAKDOWN',
  },
  MAFIA: {
    MISC_LOG: 'ENTRY_TYPE.MAFIA.MISC_LOG',
    ASCENSION_INFO: 'ENTRY_TYPE.MAFIA.ASCENSION_INFO',
    EMPTY_CHECKPOINT: 'ENTRY_TYPE.MAFIA.EMPTY_CHECKPOINT',
    CLI: 'ENTRY_TYPE.MAFIA.CLI',
  },

  LOCATION_VISIT: 'ENTRY_TYPE.LOCATION_VISIT',
  ENCOUNTER_UNKNOWN: 'ENTRY_TYPE.ENCOUNTER_UNKNOWN',
  ENCOUNTER: {
    COMBAT: 'ENTRY_TYPE.ENCOUNTER.COMBAT',
    NONCOMBAT: 'ENTRY_TYPE.ENCOUNTER.NONCOMBAT',
  },

  USE_SKILL: {
    COMBAT: 'ENTRY_TYPE.USE_SKILL.COMBAT',
    NONCOMBAT: 'ENTRY_TYPE.USE_SKILL.NONCOMBAT',
    UPKEEP_EFFECT: 'ENTRY_TYPE.USE_SKILL.UPKEEP_EFFECT',
  },
  USE_ITEM: {
    COMBAT: 'ENTRY_TYPE.USE_ITEM.COMBAT',
    NONCOMBAT: 'ENTRY_TYPE.USE_ITEM.NONCOMBAT',
  },

  EQUIP: 'ENTRY_TYPE.EQUIP',
  FAMILIAR: 'ENTRY_TYPE.FAMILIAR',
  MCD: 'ENTRY_TYPE.MCD',
}

export default ENTRY_TYPE;